version: '3.7'

services:
#  frontend:
#    stdin_open: true
#    container_name: frontend
#    build:
#      context: .
#      dockerfile: ./DockerfileFrontend
#      target: development
#    volumes:
#      - ./frontend:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3001:3000
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/DockerfileApi
      target: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: nestjsPass
      POSTGRES_USER: nestjsUser
      POSTGRES_DB: nestjsDb
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - webnet
    environment:
      PGADMIN_DEFAULT_EMAIL: dm.okhrimenko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
networks:
  webnet:
volumes:
  pgdata:
  pgadmin: